### ISSUE TITLE
Support custom Xcode install location

### ISSUE THREAD

**Issue by conath** [RobotsAndPencils/xcodes#100]
I have limited disk space on my boot volume, so I need to download and install Xcode on an external SSD. It would be great if there was an option to pass the output folder for download and install to xcodes, preferably by using an environment variable.

**Comment by interstateone** [comment]
👍 Good idea @conath! Do you prefer using an environment variable because you'd always have it set in your shell, and that way you wouldn't need to pass an argument all the time? I think we'd support both an env var and an argument, but wanted to make sure I understood first.

I'm imagining it looking something like this:
```
# command argument, which takes precedence over an environment variable if both are set
xcodes install 12.0 --destination /Volumes/Xcode

# environment variable
XCODES_DESTINATION=/Volumes/Xcode xcodes install 12.0
```

**Comment by conath** [comment]
Exactly, I‘d prefer to set the environment var in my shell once (in my case it‘s /Volumes/MEDIA/Applications/), as there’s too little disk space to even download the XIP onto my boot volume.

**Comment by interstateone** [comment]
> there’s too little disk space to even download the XIP onto my boot volume.

Ah, this might not solve the entire problem for you then. URLSession.downloadTask first downloads to a temporary directory outside our control which is on the "main" volume. I don't think we'd switch away from that API because it allows us to restart a failed download from where it left off which is valuable for large .xips. With this change xcodes would move the downloaded file from the temp directory to XCODES_DESTINATION on the other volume after it finished downloading and before it expanded the .xip, so I still think this would be a valuable thing to add.

**Comment by conath** [comment]
You‘re right, it would still be valuable to have the option to choose where the XIP is expanded. I could probably clear enough disk space for the initial download, but definitely not for the expand/install.

**Comment by art-divin** [comment]
@conath 
Unfortunately XIP command works as such it creates a cache location in /private/var/folders even if to "unxip" on an external drive completely out of built-in drive (running macOS).
I could not find a hack that would allow to completely skip the caching part.

(To be clear, xip command line utility works as:
1. expand into /private/var/folders/...
2. move expanded archive either to the location specified as an argument or into the current directory)
