### ISSUE TITLE
After installing it via Homebrew it doesn't download Xcode properly

### ISSUE THREAD

**Issue by thepoppingone** [RobotsAndPencils/xcodes#154]
When using `xcodes` in M1 Mac, it can select the xcodes nicely if they are already installed in the applications folder.

However, when trying to install directly through the `xcodes` command, it downloads a small file and installation completes from there instead of downloading the full Xcode version.

**Comment by MattKiazyk** [comment]
hi @thepoppingone 

If you browse to `/Users/<user>/Library/Application Support/com.robotsandpencils.xcodes/` you'll see any files it has tried to download and is usually a file with html in it

In the past, the is because the Apple ID you're logging in with is not a Apple Developer and it doesn't handle it properly. 

Let me know if something like that is your issue?

**Comment by MarcSteven** [comment]
Yeah I also met the issue, the error as below:
`The operation couldn’t be completed. (DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}))))
The operation couldn’t be completed. (DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}))))`

**Comment by MattKiazyk** [comment]
Hi @MarcSteven 

Usually those types of decoding errors are because you are not logged into an Apple Developer account and it's trying to parse the downloads, but it's returning as html and not json. Can you make sure you are logged in with Xcode's with an Apple ID that is tied to a developer account?

**Comment by MarcSteven** [comment]
@MattKiazyk I don't have Xcode ,I just want to download it

**Comment by thepoppingone** [comment]
Sorry I only got to work on this problem again as the M1 Mac was taken away from me. If my Apple ID is not tied to a developer account can this still work? This works fine without developer account in intel macs though.
