### ISSUE TITLE
Allow non-superuser installation

### ISSUE THREAD

**Issue by juanjonol** [RobotsAndPencils/xcodes#177]
Hi! Thank you for making this super useful tool!

Currently `xcodes` requires superuser privileges to work. As far as I know, this is required to:

- Enable developer mode, calling `/usr/sbin/DevToolsSecurity -enable` (I'm not sure what's this is for).
- Approve Xcode’s license.
- Install Xcode’s components.

None of this seems like a hard requirement that should make `xcodes` fail (Xcode will do all this on its first run anyway), so I think adding a `--no-superuser` option to `xcodes install` would make sense.

Would you accept a pull request for this?

Thank you!

**Comment by om-ha** [comment]
> Enable developer mode, calling /usr/sbin/DevToolsSecurity -enable (I'm not sure what's this is for)

It's need for hooking to another process when debugging.
- https://www.unix.com/man-page/osx/1/DevToolsSecurity/
- https://stackoverflow.com/questions/9132826/stop-developer-tools-access-needs-to-take-control-of-another-process-for-debugg

Otherwise you'd get the prompt shown in the stackoverflow answer, second link above.

However, this command should automatically be called as per the Xcode Developer Tools installer.
> When the Xcode developer tools are installed, the post-install script automatically runs this DevToolsSecurity tool to change the authorization policies
