### ISSUE TITLE
Add the ability to delete the xip file completely

### ISSUE THREAD

**Issue by tahirmt** [RobotsAndPencils/xcodes#185]
The default behavior of moving the xip file to the trash after it is installed makes sense but I think it would be beneficial to add an option to delete the file completely instead so we don't have to do the manual process of cleaning trash afterwards

**Comment by juanjonol** [comment]
+1 to this. In my case, I'm automating `xcodes` with a script, and this behavior is problematic because scripts cannot read the Trash (unless they have Full Disk Access, reducing security).

I do agree with the initial idea that [the .xip should be preserved by default](https://github.com/RobotsAndPencils/xcodes/issues/56#issuecomment-512919385), so maybe adding a `--delete-xip` flag to `xcodes install` would be the best?

**Comment by davdroman** [comment]
Additionally, I'd appreciate a `--delete-app` flag for `xcodes uninstall` as well. Moving it to the Trash alone is not really useful since it requires emptying the Trash afterwards (which takes ages compared to `rm -r`).

**Comment by fkorotkov** [comment]
This is specifically a problem when SIP is enabled and seems there is no way to programmatically clean trash.
