### ISSUE TITLE
Xcode installed in custom location not listed

### ISSUE THREAD

**Issue by TomaszLizer** [RobotsAndPencils/xcodes#244]
I am using xcodes cli installed through homebrew version: 1.1.0.
On my local machine I keep all xcode versions in `Work` folder located inside `Applications` folder so example path to xcode will be `/Applications/Work/Xcode_14.0.1.app`.
Xcodes for such scenario do not see my installed xcode versions (`xcodes installed`). If I move on of the installations directly to `Applications` folder it can be found without any issues.
I am migrating from `xcode-install` due to its "sunset" and it handled it without any problem.

**Comment by MattKiazyk** [comment]
Hi @TomaszLizer you can use the `--directory` option to specify where xcodes should look for existing versions. Without this option xcodes will look at `/Applications` by default. 

You can also use `XCODES_DIRECTORY` Environment variable instead of the above option.

Let me know if that works out for you.

**Comment by TomaszLizer** [comment]
It indeed works like a charm. Not as neat (no additional setup needed) as xcode-install which searches directories, but does the job :) 
Thanks @MattKiazyk
