### ISSUE TITLE
[Feature request] Store username in config/cache after every successful login

### ISSUE THREAD

**Issue by thii** [RobotsAndPencils/xcodes#40]
Currently, users have to enter their Apple ID username or specify `XCODES_USERNAME` environment variable every time they run the `xcodes update` or `xcodes install` commands (and also `xcodes list` for the first time). This feature will eliminate the need of asking users to type in their username every time.

## Implementation details
- If a username isn't specified with the `XCODES_USERNAME` environment variable, and there is no
username saved, prompt the user for a username.
  - If the login succeeds, then save the username.
  - If the login fails, don't save the username.
- If a username isn't specified with the `XCODES_USERNAME` environment variable, and there is a username saved, use that username for login and don't prompt the user for a username.
- If a username is specified with the `XCODES_USERNAME` environment variable, use that username for login (don't check for a saved username, don't prompt the user for a username).
  - If the login succeeds, then save the username.
  - If the login fails, don't save the username.

**Comment by interstateone** [comment]
I initially avoided doing this in order to match xcode-install's behaviour, but I think this change would be good for using xcodes on personal development machines.

I think this could work like this, let me know what you think:

- If a username isn't specified with the XCODES_USERNAME environment variable, and there is no 
username saved, prompt the user for a username.
    - If the login succeeds, then save the username.
    - If the login fails, don't save the username.
- If a username isn't specified with the XCODES_USERNAME environment variable, and there is a username saved, use that username for login and don't prompt the user for a username.
- If a username is specified with the XCODES_USERNAME environment variable, don't check for a saved username, don't prompt the user for a username and don't save the username regardless of success.

**Comment by thii** [comment]
> If a username is specified with the XCODES_USERNAME environment variable, don't check for a saved username, don't prompt the user for a username and don't save the username regardless of success.

This would make users unable to change the saved username later. I think it's more reasonable to save the username if a username is specified with the XCODES_USERNAME and it's different from the saved one.

**Comment by interstateone** [comment]
That's a good point. I can't imagine that occurring very often for personal machines, but we should make sure users don't get stuck.

I had an alternative solution in mind, but using XCODES_USERNAME as you've proposed will end up being a simpler and more consistent solution even though it requires knowing how to specify the XCODES_USERNAME environment variable. Documentation of this seems appropriate for should be an edge case.

Can please you add those bullet points with your suggested change to the issue description?

**Comment by thii** [comment]
I updated the issue description.
