### ISSUE TITLE
Allow .xip to be persisted after install

### ISSUE THREAD

**Issue by daveanderson** [RobotsAndPencils/xcodes#56]
I made the mistake of leaving Xcode 11b3 on my machine when Xcode11b4 was being installed and ended up with Xcode 11b4 thinking that it contained modules with the wrong version of Swift.

I'm on a very poor network connection (hotel) and instead of unarchiving the previously downloaded .xip I have to redownload.

It may be useful to have a `--preserveXIP` option where the .xip will be revealed in the finder for someone to store for future use.

**Comment by interstateone** [comment]
One concern I have with this suggestion is that the user would need to know to use this flag before they've hit potential issues. An alternative might be to move the .xip to the Trash instead of deleting it so that there is a recovery option when issues with installation are discovered after the fact. I like this option at first glance because the happy path remains automatic.

Keeping .xips has other use cases though, like archiving or caching on a local network for other computers to install from. This might be worth a new `download` command, which would work with the half-implemented `install --url XIP_URL` command and flag. That's probably a separate enhancement to implement though.
