### ISSUE TITLE
Document syntax for downloading beta/GM seeds

### ISSUE THREAD

**Issue by landonepps** [RobotsAndPencils/xcodes#80]
It's not inherently clear how to download a GM seed from `xcodes`.
I tried a bunch of different ways before landing upon `xcodes install 11.2.1GM\ Seed`.

![image](https://user-images.githubusercontent.com/1572318/68327514-bc213080-008a-11ea-8314-81bff04d0e37.png)

It would be great if you could add an example for downloading a beta and a GM seed to `--help` and to the repo's readme. I'm sure I'm not the only one who had to try a bunch of different things to figure it out.

**Comment by interstateone** [comment]
Hey Landon, thanks for opening this issue. Sorry that this was less obvious than it could've been, that's frustrating.

I know this doesn't help you at this point, but in the future: you should be able to specify those versions the way it's spelled in the `xcodes list` command, like `xcodes install 11.2.1 gm seed`. The build number (in parentheses) is printed for pre-release versions because sometimes it's useful to see if Apple has changed it at all (sometimes silently) but you shouldn't need to specify it to disambiguate what version you're installing.

I agree the way it works right now could be more clear, and so I'll leave this issue open to address with some docs. I think in the future it would be nice if xcodes didn't require such a precise version identifier in cases like this, too, so that your first command would be sufficient if its unambiguous.

**Comment by landonepps** [comment]
Ah, I just assumed that you couldn't put spaces in the version. I was downloading the betas with someting like `xcodes install 11.1.1beta2` and I saw that it would insert a space so I figured that was the standard way of doing it.

**Comment by interstateone** [comment]
@landonepps I've opened #81 and I'd appreciate it if you could take a look and let me know if you think it would resolve this issue. Thanks again for suggesting this change 😄
